version: 2
jobs:

  # Build and verify the generated HTML
  build:
    docker:
      - image: rdclda/ci-vuepress:latest
    working_directory: ~/rdc-blogs
    steps:
      # Checkout the repository
      - checkout
      
      # Build with Vuepress
      - run: 
          name: Build the Vuepress static content
          command: vuepress build docs

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/rdc-blogs
          # Must be relative path from root
          paths:
             - dist/

  # Validate the generated HTML
  validate:
    docker:
      - image: rdclda/ci-htmlproofer:latest
    working_directory: ~/rdc-blogs
    environment:
      VUEPRESS_BUILD_DIR: dist
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/rdc-blogs

      # Test the generated HTML
      - run:
          name: Test our generated HTML files
          command: |
             echo "Disabled HTML proofing for now..."
          # command: |
          #   htmlproofer $VUEPRESS_BUILD_DIR --allow-hash-href --check-html \
          #   --empty-alt-ignore --disable-external


  # Publish the generated HTML to the RDC Website to PCF
  publish_pcf:
    docker:
      - image: rdclda/ci-cloudfoundry:latest
    working_directory: ~/rdc-blogs
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/rdc-blogs

      # Publish into separate folder
      - deploy: 
          name: Upload content to Pivotal CloudFoundry
          command: |
            cf login -a $CF_API_ENDPOINT -o $CF_ORG -u $CF_USER -p $CF_PASS -s $CF_SPACE && \
            cf push $APP_NAME -d $CF_DOMAIN -n rdc-blogs -s cflinuxfs3 -p ./dist

# Glue the jobs together
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - validate:
          requires:
            - build
      - publish_pcf:
          requires:
            - validate
          filters:
            branches:
              only: master